name: Publish Docker Community image tags

on:
  push:
    tags:
      - '**'           # Push events to every tag including hierarchical tags like

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
       uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      
      with:	    
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: tiledesk/design-studio
        tag_with_ref: true

    - name: Build and push
       uses: docker/build-push-action@v4

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: tiledesk/design-studio:latest